### ISSUE TITLE
Verify Bioportal can work with OntoloBridge

### ISSUE THREAD

**Issue by sjeschonek** [OntoloBridge/ontolobridge-project#88]
@graybeal please add more details

@whinis will need to work with BioPortal team to ensure authentication system is compatible

**Comment by graybeal** [comment]
Please coordinate with Misha Dorf to make sure the authentication system adopted for Ontolobridge can be integrated into BIoPortal/OntoPortal gracefully.

It may be worth also consulting with Atti Egyedi (egyedia@) if you are thinking about the OAuth route, due to his knowledge of Keycloak and the possibility we might want to link systems (like CEDAR) someday.

**Comment by whinis** [comment]
It appears that after confirming with @mdorf the new authentication system works with bioportal
